"""add model_profile_scores to session_result"""

revision = '427a7479ba73'
down_revision = '20260425_0004'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_eye_tracking_features_session_id', 'eye_tracking_features', type_='unique')
    op.drop_index('ix_eye_tracking_features_session_id', table_name='eye_tracking_features')
    op.create_index(op.f('ix_eye_tracking_features_session_id'), 'eye_tracking_features', ['session_id'], unique=True)
    op.add_column('session_results', sa.Column('model_profile_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default='{}'))
    op.drop_constraint('uq_session_results_session_id', 'session_results', type_='unique')
    op.drop_index('ix_session_results_session_id', table_name='session_results')
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=True)
    op.drop_constraint('uq_voice_features_session_id', 'voice_features', type_='unique')
    op.drop_index('ix_voice_features_session_id', table_name='voice_features')
    op.create_index(op.f('ix_voice_features_session_id'), 'voice_features', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_features_session_id'), table_name='voice_features')
    op.create_index('ix_voice_features_session_id', 'voice_features', ['session_id'], unique=False)
    op.create_unique_constraint('uq_voice_features_session_id', 'voice_features', ['session_id'])
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.create_index('ix_session_results_session_id', 'session_results', ['session_id'], unique=False)
    op.create_unique_constraint('uq_session_results_session_id', 'session_results', ['session_id'])
    op.drop_column('session_results', 'model_profile_scores')
    op.drop_index(op.f('ix_eye_tracking_features_session_id'), table_name='eye_tracking_features')
    op.create_index('ix_eye_tracking_features_session_id', 'eye_tracking_features', ['session_id'], unique=False)
    op.create_unique_constraint('uq_eye_tracking_features_session_id', 'eye_tracking_features', ['session_id'])
    # ### end Alembic commands ###
