"""add_parent_role_and_relation"""

revision = '7d0409e86d7a'
down_revision = 'f39325e0bfe7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'parent'")
    op.add_column('student_profiles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_profiles', 'users', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'parent_id')
    # ### end Alembic commands ###
